INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris can make a class that is both abstract and final.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris serializes objects straight into human skulls.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris doesn’t deploy web applications, he round-house kicks them into the server.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris always uses his own design patterns, and his favorite is the Round-house Kick.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris could use anything in java.util.* to kill you, including the javadocs.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris can hit you so hard your web app will turn into a swing application, and a very bad swing application containing lots of icons of human skulls.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris demonstrated the meaning of Float.POSITIVE_INFINITY by counting to it, twice.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('A synchronize doesn’t protect against Chuck Norris, if he wants the object, he takes it.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris doesn’t use javac, he codes java by using a binary editor on the class files.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris’ java code never needs to be optimized. His code is so fast that it broke the speed of light during a test run in Sun’s labs killing 37 people.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('When someone attempts to use one of Chuck Norris’ deprecated methods, they automatically get a round-house kick to the face at compile time.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('The java.lang package originally contained a ChuckNorris class, but it punched its way out the package during a design review and round-house kicked Bill Joy in the face.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris never has a bug in his code, EVER!');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris doesn’t write code. He stares at a computer screen until he gets the program he wants.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Code runs faster when Chuck Norris watches it.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris’ binary edited classes ignore Java bytecode verifier.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris methods doesn’t catch exceptions because no one has the guts to throw any at them.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris will cast a value to any type just by staring at it.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('If you get a ChuckNorrisException you’ll probably die.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris is the only one who can use goto and const in Java.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris can compile Java code in .NET Framework, obviously just by staring at it.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck don\'t need to catch an Exception because Java is afraid of the “flying tornado kick” at the moment it throws.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris’s code can round-house kick all other Java Objects’ privates.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Java visibility levels are public, default, protected, private and “protected by Chuck Norris”, don’t try to access a field with this last modifier!!');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris eats JavaBeans and Round-house Kicks JavaServer Faces!');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris can divide by 0!');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Garbage collector only runs on Chuck Norris code to collect the bodies.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris code uses aggressive heap natively.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Every single line code of Chuck Norris runs in real time. Even in a multi threading application.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('When a CPU load a Chuck Norris class file, it doubles the speed.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris can execute 64bit length instructions in a 32bit CPU.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris implements “Indestructible”. All the other creatures implements “Killable”.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris only program Java web applications to get a .WAR in the end.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris once round-house kicked a Java class very hard. The result is known as a inner class.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris can do multiple inheritance in Java.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('JVM never throws exceptions to Chuck Norris, not anymore. 753 killed Sun engineers is enough.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris doesn’t need unit tests because his code always work. ALWAYS.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris extends God.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris workstation has so memory and it’s so powerful that he could run all java applications in the world and get 2% of resources usage.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris codes generics since 1.3.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris’ classes can’t be decompiled… don’t bother trying.');
