INSERT INTO chuck_quotes.quotes (text) VALUES ('When Alexander Bell invented the telephone he had 3 missed calls from Chuck Norris.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('There used to be a street named after Chuck Norris, but it was changed because nobody crosses Chuck Norris and lives..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Fear of spiders is aracnaphobia, fear of tight spaces is chlaustraphobia, fear of Chuck Norris is called Logic.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('If you rate this 5 roundhouse kicks, then Chuck Norris WILL roundhouse kick Justin Bieber\s ass..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris has already been to Mars; that\'s why there are no signs of life..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris died 20 years ago, Death just hasn\'t built up the courage to tell him yet..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Some magicans can walk on water, Chuck Norris can swim through land..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris and Superman once fought each other on a bet. The loser had to start wearing his underwear on the outside of his pants..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Death once had a near-Chuck Norris experience.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris can cut through a hot knife with butter.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris once kicked a horse in the chin. Its decendants are known today as Giraffes..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris has a grizzly bear carpet in his room. The bear isn\'t dead it is just afriad to move..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris will never have a heart attack. His heart isn\'t nearly foolish enough to attack him..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris can win a game of Connect Four in only three moves..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris once got bit by a rattle snake........ After three days of pain and agony ..................the rattle snake died.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('When Chuck Norris does a pushup, he isn\'t lifting himself up, he\'s pushing the Earth down..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('There is no theory of evolution. Just a list of animals Chuck Norris allows to live..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris tells the Flight Attendant to remain seated..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris doesn’t wear a watch. HE decides what time it is..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('The original title for Alien vs. Predator was Alien and Predator vs Chuck Norris..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris doesn\'t read books. He stares them down until he gets the information he wants..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris made a Happy Meal cry..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris has never worn glasses in his life. If he can\'t see it, then it doesn\'t exist..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Some people wear Superman pajamas. Superman wears Chuck Norris pajamas..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Outer space exists because it\'s afraid to be on the same planet with Chuck Norris..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('If you spell Chuck Norris in Scrabble, you win. Forever..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris\' hand is the only hand that can beat a Royal Flush..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris was in all 6 Star Wars movies............... As The Force..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris sleeps with a pillow under his gun..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris had a starring conntest with a miror ... And won.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris can unscramble scrambled eggs..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris is the only man to ever defeat a brick wall in a game of tennis..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris knows the last digit of pi..');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris can divide by zero.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Ghosts sit around the campfire and tell Chuck Norris stories.');
INSERT INTO chuck_quotes.quotes (text) VALUES ('Chuck Norris played Russian Roulette with a fully loaded gun and won..');